import RoadmapMilestone from 'types/RoadmapMilestone'

export const getById = (id: number): RoadmapMilestone => {
  const roadmapMilestone: RoadmapMilestone = {
    milestones: [
      {
        goals: [
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-04-04'),
            images: [],
            name: 'Create repository',
            shortDescription: '',
            startDate: new Date('2021-03-13'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-04-04'),
            images: [],
            name: 'Install ReactJS and basic structure',
            shortDescription: '',
            startDate: new Date('2021-04-04'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-04-18'),
            images: [],
            name: 'Define initial Roadmap types',
            shortDescription: '',
            startDate: new Date('2021-04-04'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'It will be place and fixed in the application top',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Header v1. Create Header component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'This feature indcludes responsive styles and basic html',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Board v1. Create Board component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'This feature indcludes responsive styles and basic html',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Milestone v1. Create Milestone component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'This feature indcludes responsive styles and basic html',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Goal v1. Create Goal component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description:
              'With this feature we will can get a fake data from a fake service. It is necessary to future real connections.',
            finishDate: new Date('2021-05-09'),
            images: [],
            name: 'Add services and react query structure',
            shortDescription: '',
            startDate: new Date('2021-05-01'),
            status: 'Done',
            tags: [],
          },
        ],
        finishDate: new Date('2021-05-09'),
        name: '0.1',
        startDate: new Date('2021-03-13'),
        status: 'Done',
      },
      {
        goals: [
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-05-10'),
            images: [],
            name: 'Check and update dependencies',
            shortDescription: '',
            startDate: new Date('2021-05-09'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-05-09'),
            images: [],
            name: 'Add Svg template to import them',
            shortDescription: '',
            startDate: new Date('2021-05-09'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'We will updated Milestone component with new styles and expandable behaviour',
            finishDate: new Date('2021-07-17'),
            images: [],
            name: 'Milestone v2',
            shortDescription: '',
            startDate: new Date('2021-05-10'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'We will updated Goal component with new styles',
            finishDate: new Date('2021-07-17'),
            images: [],
            name: 'Goal v2',
            shortDescription: '',
            startDate: new Date('2021-05-10'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: 'It is required to add quailty to code',
            finishDate: new Date('2021-07-20'),
            images: [],
            name: 'Add tests infrastructure',
            shortDescription: '',
            startDate: new Date('2021-05-09'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: 'Roboto will be added as default font with his several font weight',
            finishDate: new Date('2021-07-24'),
            images: [],
            name: 'Roboto as default font',
            shortDescription: '',
            startDate: new Date('2021-07-20'),
            status: 'Done',
            tags: [],
          },
        ],
        finishDate: new Date('2021-07-24'),
        name: '0.2',
        startDate: new Date('2021-05-29'),
        status: 'Done',
      },
      {
        goals: [
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'Allow categorize goals to structure them',
            images: [],
            name: 'Milestone v3',
            finishDate: new Date('2021-09-17'),
            shortDescription: '',
            startDate: new Date('2021-08-29'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'Add dialog component when click in a goal to expand it information',
            images: [],
            name: 'Goal v3',
            shortDescription: '',
            startDate: new Date('2021-09-17'),
            status: 'Ongoing',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'Create dialog component',
            images: [],
            name: 'Dialog v1',
            shortDescription: '',
            startDate: new Date('2021-09-21'),
            status: 'Ongoing',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description:
              'Add context infrastructure to store data and it data can be shared between whole application components.',
            finishDate: new Date('2021-09-21'),
            images: [],
            name: 'Context to store data',
            shortDescription: '',
            startDate: new Date('2021-09-17'),
            status: 'Done',
            tags: [],
          },
        ],
        name: '0.3',
        startDate: new Date('2021-08-29'),
        status: 'Ongoing',
      },
    ],
    name: 'Roadmap Milestone',
    startDate: new Date('2021-03-13'),
  }

  return roadmapMilestone
}
