import RoadmapMilestone from 'types/RoadmapMilestone'

export const getById = (id: number): RoadmapMilestone => {
  const roadmapMilestone: RoadmapMilestone = {
    milestones: [
      {
        goals: [
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-04-04'),
            images: [],
            name: 'Create repository',
            shortDescription: '',
            startDate: new Date('2021-03-13'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-04-04'),
            images: [],
            name: 'Install ReactJS and basic structure',
            shortDescription: '',
            startDate: new Date('2021-04-04'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-04-18'),
            images: [],
            name: 'Define initial Roadmap types',
            shortDescription: '',
            startDate: new Date('2021-04-04'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'It will be place and fixed in the application top',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Header v1. Create Header component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'This feature indcludes responsive styles and basic html',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Board v1. Create Board component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'This feature indcludes responsive styles and basic html',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Milestone v1. Create Milestone component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'This feature indcludes responsive styles and basic html',
            finishDate: new Date('2021-05-01'),
            images: [],
            name: 'Goal v1. Create Goal component',
            shortDescription: '',
            startDate: new Date('2021-04-18'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description:
              'With this feature we will can get a fake data from a fake service. It is necessary to future real connections.',
            finishDate: new Date('2021-05-09'),
            images: [],
            name: 'Add services and react query structure',
            shortDescription: '',
            startDate: new Date('2021-05-01'),
            status: 'Done',
            tags: [],
          },
        ],
        finishDate: new Date('2021-05-09'),
        name: '0.1',
        startDate: new Date('2021-03-13'),
        status: 'Done',
      },
      {
        goals: [
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-05-10'),
            images: [],
            name: 'Check and update dependencies',
            shortDescription: '',
            startDate: new Date('2021-05-09'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: '',
            finishDate: new Date('2021-05-09'),
            images: [],
            name: 'Add Svg template to import them',
            shortDescription: '',
            startDate: new Date('2021-05-09'),
            status: 'Done',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'We will updated Milestone component with new styles and expandable behaviour',
            images: [],
            name: 'Milestone v2',
            shortDescription: '',
            startDate: new Date('2021-05-10'),
            status: 'Ongoing',
            tags: [],
          },
          {
            category: {
              name: 'Components',
              color: 'green',
            },
            description: 'We will updated Goal component with new styles',
            images: [],
            name: 'Goal v2',
            shortDescription: '',
            startDate: new Date('2021-05-10'),
            status: 'Ongoing',
            tags: [],
          },
          {
            category: {
              name: 'Infrastructure',
              color: 'red',
            },
            description: 'It is required to add quailty to code',
            images: [],
            name: 'Add tests infrastructure',
            shortDescription: '',
            startDate: new Date('2021-05-09'),
            status: 'Ongoing',
            tags: [],
          },
        ],
        name: '0.2',
        startDate: new Date('2021-05-29'),
        status: 'Ongoing',
      },
    ],
    name: 'Roadmap Milestone',
    startDate: new Date('2021-03-13'),
  }

  return roadmapMilestone
}
